# Workflow para botting agresivo
#.github/workflows/aggressive_botting.yml
name: Aggressive Botting

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fanpage: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot for fanpage \${{ matrix.fanpage }}
        env:
          TIKTOK_API_KEY: \${{ secrets.TIKTOK_API_KEY_FANPAGE_\${{ matrix.fanpage }} }}
          INSTAGRAM_API_KEY: \${{ secrets.INSTAGRAM_API_KEY_FANPAGE_\${{ matrix.fanpage }} }}
          FANPAGE_NUMBER: \${{ matrix.fanpage }}
        run: |
          python scripts/bot_engagement.py --fanpage=\${{ matrix.fanpage }}

      - name: Upload bot logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bot-logs-fanpage-\${{ matrix.fanpage }}
          path: logs/bot_fanpage_\${{ matrix.fanpage }}.log