name: Edit Videos

on:
  schedule:
    - cron: '30 */6 * * *'
  workflow_dispatch:

jobs:
  edit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Edit videos
        run: python scripts/batch_edit.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: editing-logs
          path: logs/
