# .github/workflows/generate_videos.yml
name: Generate Videos

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p media/GeneratedVideos
          mkdir -p logs

      - name: Generate videos
        env:
          RUNWAY_API_KEY: \${{ secrets.RUNWAY_API_KEY }}
          GOOGLE_CREDENTIALS: \${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python scripts/auto_generate.py

      - name: Upload to Google Drive
        env:
          GOOGLE_CREDENTIALS: \${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python scripts/upload_to_drive.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: generation-logs
          path: logs/
